name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Updated to v3 for better stability
        with:
          fetch-depth: 0
          lfs: true # Recommended if your search engine uses large model files

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://MalakMohamed21:$HF_TOKEN@huggingface.co/spaces/MalakMohamed21/Egypt_History_Search_Engine main
